/**
 * AUTHENTICATION TYPES
 */

export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_FAILED = "SIGN_IN_FAILED";
export const SIGN_OUT_SUCCESS = "SIGN_OUT_SUCCESS";
export const SIGN_OUT_FAILED = "SIGN_OUT_FAILED";

export const CONNECT_SOCKET = "CONNECT_SOCKET";
export const DISCONNECT_SOCKET = "DISCONNECT_SOCKET";

export const LOAD_USER_DATA_SUCCESS = "LOAD_USER_DATA_SUCCESS";
export const LOAD_USER_DATA_FAILED = "LOAD_USER_DATA_FAILED";

export const ADD_CONTACT_SUCCESS = "ADD_CONTACT_SUCCESS";
export const ADD_CONTACT_FAILED = "ADD_CONTACT_FAILED";

export const SELECT_CONTACT = "SELECT_CONTACT";
export const SELECT_CHAT = "SELECT_CHAT";

export const SEND_NEW_MESSAGE_BE_SUCCESS = "SEND_NEW_MESSAGE_BE_SUCCESS";
export const SEND_NEW_MESSAGE_BE_FAILED = "SEND_NEW_MESSAGE_BE_FAILED";
export const SEND_NEW_MESSAGE_FE = "SEND_NEW_MESSAGE_FE";
export const SEND_MESSAGE_SOCKET = "SEND_MESSAGE_SOCKET";

export const RESEND_MESSAGE = "RESEND_MESSAGE";

export const RECEIVE_NEW_MESSAGE = "RECEIVE_NEW_MESSAGE";
export const UPDATE_READ_NOTICE = "UPDATE_READ_NOTICE";
export const UPDATE_READ_STATUS = "UPDATE_READ_STATUS";

export const DELETE_MESSAGE = "DELETE_MESSAGE";
export const DELETE_MESSAGE_FAILED = "DELETE_MESSAGE_FAILED";
export const DELETE_MESSAGE_UNSENT = "DELETE_MESSAGE_UNSENT";
export const DELETE_MESSAGE_NOTICE = "DELETE_MESSAGE_NOTICE";
export const DELETE_MESSAGE_NOTICE_FAILED = "DELETE_MESSAGE_NOTICE_FAILED";

export const CLEAN_UP_SESSION = "CLEAN_UP_SESSION";
